### ISSUE TITLE
Translator name in byline missing

### ISSUE THREAD

**Issue by rhettbutler** [martinosmartinos/Mongabay-Wordpress-Theme#1]
The translator credit is missing in the byline. We discussed and decided it's best to put this next to the date.

**Comment by martinosmartinos** [comment]
Agree!

**Comment by martinosmartinos** [comment]
#16

**Comment by rhettbutler** [comment]
Yay!

![azureus](https://user-images.githubusercontent.com/3682119/29104097-6eda6514-7c78-11e7-9803-182bb7c71c2d.gif)
