### ISSUE TITLE
The last story overlays the right rail in Mac Safari

### ISSUE THREAD

**Issue by rhettbutler** [martinosmartinos/Mongabay-Wordpress-Theme#11]
See under "Most Read"

![screen shot 2017-08-03 at 4 10 53 pm](https://user-images.githubusercontent.com/3682119/28988334-32117f98-7924-11e7-8378-2b2a715e69d3.png)

**Comment by martinosmartinos** [comment]
Should be fixed with #20

**Comment by rhettbutler** [comment]
Looks good!
