### ISSUE TITLE
Image optimization for mobile

### ISSUE THREAD

**Issue by rhettbutler** [martinosmartinos/Mongabay-Wordpress-Theme#13]
As we've discussed

**Comment by martinosmartinos** [comment]
Featured cover image size for mobile devices is now set to 'medium' instead. For desktop it remains 'large'. Covered in #22

**Comment by rhettbutler** [comment]
Good solution

**Comment by martinosmartinos** [comment]
Additionally we are now loading only one featured image at the time when accessed from mobile device. Before these were hidden via css. Changes in #26
