### ISSUE TITLE
Right and left aligned image captions span the entire article column

### ISSUE THREAD

**Issue by rhettbutler** [martinosmartinos/Mongabay-Wordpress-Theme#2]
Example: 
https://news.mongabay.com/2017/06/footprints-in-the-forest-the-future-of-the-sumatran-rhino/
https://news.mongabay.com/2017/08/guyanas-road-to-brazil-to-presents-opportunity-and-challenge/
<img width="888" alt="screen shot 2017-08-03 at 2 07 09 pm" src="https://user-images.githubusercontent.com/3682119/28977541-47340544-78f7-11e7-8825-112bff7c973c.png">

**Comment by martinosmartinos** [comment]
Resolved with #30
