### ISSUE TITLE
A second page template for news

### ISSUE THREAD

**Issue by rhettbutler** [martinosmartinos/Mongabay-Wordpress-Theme#32]
Hi Martin,
It is possible to have a second page template for pages on news? I'd like to have a different set of widgets to apply to a few specific pages.
Thanks,
Rhett

**Comment by martinosmartinos** [comment]
Isn't it better having multiple sidebars instead and render widgets accordingly?

**Comment by rhettbutler** [comment]
I didn't know that was an option. Yes, that sounds better. To be sure we're on the same thinking, I could select a specific side bar for a certain page? An example is this page: https://news.mongabay.com/statistics/ which only the staff uses. We used to have different "most read" widgets on the sidebar instead of the donate, newsletter, etc widgets.

**Comment by martinosmartinos** [comment]
Solved with https://github.com/martinosmartinos/Mongabay-Wordpress-Theme/commit/29b2d47cb612f0eae81d9baeb3d06ebc3afbea5b
