### ISSUE TITLE
Updating published posts using too much memory

### ISSUE THREAD

**Issue by WillieShubert** [martinosmartinos/Mongabay-Wordpress-Theme#51]
Hey @martinosmartinos 
I've been troubleshooting consistent HTTP 500 errors when updating certain posts. I spoke to the host support folks about the resource issue and they helped me identify two error messages. Can you check and see if there are issues with out theme that might be causing the memory issues to occur?

PHP Catchable fatal error: Object of class WP_Error could not be converted to string in ../single.php on line 36

PHP Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 56852480 bytes) ../object-cache.php on line 425

**Comment by WillieShubert** [comment]
We have been able to temporarily resolve this issue by increasing the memory limit on the .htaccess file. 

The tech said this:
"I  added a line to your .htaccess so that you can set the definitions in your wp-config.php to higher than 512mb. "php_value memory_limit 1024M" is the line, so you'd be free to add it to the .htaccess of any of your installs.

**Comment by martinosmartinos** [comment]
512mb is quite small ram size and taking in account how many plugins are triggered on post modification/publishing it is quite normal to increase memory. All plugins responsible for publishing to instant articles or apple news are quite resource greedy.
