### ISSUE TITLE
Page Columns Layout Broken

### ISSUE THREAD

**Issue by WillieShubert** [martinosmartinos/Mongabay-Wordpress-Theme#52]
Hey @martinosmartinos ,

The page layouts on the topic and location landing pages is currently broken and is only displaying one column.  It looks like an issue with the "post-wrapper-news.row"

![screen shot 2018-05-10 at 3 19 38 pm](https://user-images.githubusercontent.com/3870349/39897140-d3e39686-5465-11e8-84e5-b3d32511a232.png)

**Comment by martinosmartinos** [comment]
Did you clear page cache as columns are coming from script?
