### ISSUE TITLE
Two column page layouts not rendering for some low-bandwidth users 

### ISSUE THREAD

**Issue by WillieShubert** [martinosmartinos/Mongabay-Wordpress-Theme#56]
We've witnessed a couple of instances where people with a slow connection can have their asynchronous page load interrupted which the results in a broken looking page. Any ideas for how to address this problem: Please see this screenshot for an example of what users see when this happens:

<img width="849" alt="display prob 2" src="https://user-images.githubusercontent.com/3870349/43595220-ff7532de-9630-11e8-904a-870bbaac7b9e.png">

I just reviewed what happens when pages are requested and the first thing loaded is the basic structure of the page and all the images referenced in the index.html file. Once these are loaded, all of the javascript is requested and run at once using an optimization tool called rocket-loader from cloudflare. I see the value of this approach as the initial page load is really fast since javascript requests are deferred and loaded asynchronously.

However, the javascript library responsible for the final layout of the page, salvattore, is also deferred and I think this may be causing the issue. Since the download of the JS library is being stalled until after the index is loaded we may be introducing a delay in the display of the proper layout until rocket-loader completes its job asynchronously.  

For most people, this page loading process is pretty much instantaneous and thus not noticeable.

**Comment by martinosmartinos** [comment]
Isn't it more of a end-user browser cache which needs cleaning? Cache age
is set to quite long period of time now.
