### ISSUE TITLE
Add Whatsapp share icon into the post template 

### ISSUE THREAD

**Issue by WillieShubert** [martinosmartinos/Mongabay-Wordpress-Theme#63]
Hey @martinosmartinos,

We have a request to add in a new sharing option, WhatsApp, to posts. This feature is requested to be placed into the div class 'single-article-meta', div class 'social' section of the post template. 

This is what this section currently looks like: 

![screen shot 2018-08-17 at 10 57 26 am](https://user-images.githubusercontent.com/3870349/44281359-60138780-a20c-11e8-968c-5d7b3918c07e.png)

Can you add that in the next week or two?

**Comment by martinosmartinos** [comment]
Must be straight forward by hooking up WhatsApp://send?text=..... URL to a
button.
