### ISSUE TITLE
Translation bylines not saving to DB or displaying in Aside post templates

### ISSUE THREAD

**Issue by WillieShubert** [martinosmartinos/Mongabay-Wordpress-Theme#70]
When adding in translator byline information on aside posts, the process for saving the post takes a very long time to complete. When the post update/save is completed, the byline information is stripped from the story which suggests it is not being written to the database.

**Comment by martinosmartinos** [comment]
Does it happen on a news site and does draft article show byline on a
front-end despite not being shown at backend?

**Comment by martinosmartinos** [comment]
Combination of plugins installed was causing this error. Fixed.
