### ISSUE TITLE
WildTech Front page featured stories not updating properly.

### ISSUE THREAD

**Issue by WillieShubert** [martinosmartinos/Mongabay-Wordpress-Theme#84]
Hey @martinosmartinos,

Following the change in approach to tagging stories to appear on wildtech.mongabay.com, the featured stories at the top of the front page are not responding to the "Featured Story" tag in the "More Fields" section of the wp-admin post editor.

This recent [post](https://news.mongabay.com/wp-admin/post.php?post=211159&action=edit) is showing correctly as the most recent but it isn't currently featured despite being tagged correctly. 

Thanks for the help with this!

**Comment by martinosmartinos** [comment]
It looks like for a slider code was not updated to pull posts tagged with 'technology' and still showing results based on assigned category:

https://github.com/martinosmartinos/Mongabay-Wordpress-Theme/blob/master/partials/section-slider.php

**Comment by martinosmartinos** [comment]
Will fix it coming days.

**Comment by martinosmartinos** [comment]
Fixed in #85

**Comment by WillieShubert** [comment]
Thanks Martin. I'll share this with editors and ask if it's working for
them.

**Comment by martinosmartinos** [comment]
@WillieShubert indeed, just noticed typo and corrected in #86 It should be live so please check if it works as expected.
