### ISSUE TITLE
Integrate Spot.IM Comments

### ISSUE THREAD

**Issue by rhettbutler** [martinosmartinos/Mongabay-Wordpress-Theme#9]
Replace Facebook comment box.

Notes from Spot.IM

Please follow this guide to implement Spot.IM:
https://spotim-jira.atlassian.net/wiki/x/v5wE

You'll see a parameter, SPOT_ID, yours are-

Mongabay.com: sp_8TLFqmLV

cn.mongabay.com: sp_A3SnHcgH

de.mongabay.com: sp_ZwMqGXOu

es.mongabay.com: sp_1xRecNST

fr.mongabay.com: sp_sbJbR9zO

mongabay.co.id: sp_XByh4fod

it.mongabay.com: sp_NNvA5Ksj

jp.mongabay.com: sp_elj4Klyl

pt.mongabay.com: sp_yZlmuqld

**Comment by martinosmartinos** [comment]
There must be additional work done on rearranging elements loaded along spot.im plugin activation. As a reference we could use nytimes and their style showing comments in sliding out panel. Right now default setup looks way too busy and we starting to loose that "less is more" look.
