### ISSUE TITLE
Update Philippines.Mongabay.com Logo and Header Menu 

### ISSUE THREAD

**Issue by WillieShubert** [martinosmartinos/Mongabay-Wordpress-Theme#93]
Hey @martinosmartinos,

We're setting up a microsite in a similar fashion as [srilanka.mongabay.com](srilanka.mongabay.com) for the Philippines on this subdomain: [https://philippines.mongabay.com](https://philippines.mongabay.com)

Can you please make a menu item pointed to this [link](https://philippines.mongabay.com/about-mongabay-environews-philippines) and update the logo with the following png.

![mongabay_environews_phillippines_logo](https://user-images.githubusercontent.com/3870349/58737068-ff2cf880-83b4-11e9-8af0-375fff974680.png)

Thank you very much!

**Comment by WillieShubert** [comment]
Hey @martinosmartinos , I updated the logo files on the server but it doesn't seem to update even after a full clear cache. I kept the same file path so I wouldn't need to change the theme code but it didn't work for the SVG.

This is odd because the PNG version did change to the new logo. See: https://philippines.mongabay.com/wp-content/themes/mongabay_v1/img/logo/mongabay_logo_philippines.png

**Comment by martinosmartinos** [comment]
Hi Willie,
can you access svg file the same way as you do PNG?

**Comment by WillieShubert** [comment]
When I access the SVG file in the same way as the PNG, it shows the old one. However, when I access the logo folder on the server over SFTP the SVG file is the new logo.

**Comment by martinosmartinos** [comment]
Must be cloudfront cache then. You have to invalidate it.

**Comment by WillieShubert** [comment]
We just had to wait it out. It's live now.
